server:
  port: 8083

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/
    username: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    open-in-view: false