CREATE SCHEMA IF NOT EXISTS tenant_3;

    CREATE TABLE IF NOT EXISTS tenant_3.tenant
    (
        tenant_id VARCHAR(255) NOT NULL,
        schema    VARCHAR(255),
        CONSTRAINT pk_tenant PRIMARY KEY (tenant_id)
        );
    
    CREATE TABLE IF NOT EXISTS tenant_3.employee
    (
        id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        fullname VARCHAR(255),
        CONSTRAINT pk_employee PRIMARY KEY (id)
        );
    
    CREATE TABLE IF NOT EXISTS tenant_3.payment
    (
        id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        employeeId BIGINT,
        amount      BIGINT,
        CONSTRAINT pk_payment PRIMARY KEY (id)
        );
    
    CREATE TABLE IF NOT EXISTS tenant_3.receipt
    (
        id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        employeeId BIGINT,
        amount      BIGINT,
        issuedAt   TIMESTAMP WITHOUT TIME ZONE,
        CONSTRAINT pk_receipt PRIMARY KEY (id)
        );